config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :offers
  resources :orders

  root to: "offers#index"

  post 'offers/:id' => 'offers#create_order', as: :create_order

  get   'users/settings' => 'users#settings', as: :user_settings
  patch 'users/settings' => 'users#update_settings'
  get   'users'          => 'users#index', as: :users

end

app/models/offer.rb
class Offer < ActiveRecord::Base
  has_many :orders

  has_attached_file :image, :styles => { :medium => "500x500>", :thumb => "100x100>" },
  :default_url => "/images/missing.png"

  validates_attachment :image,
  :content_type => { :content_type => ["image/jpeg", "image/gif", "image/png"] },
  :size => { :in => 1..800.kilobytes }

  validates :name, presence: true
  validates :name, length: { minimum: 2 }
  validates :description, length: { in: 10..200 }
  validates :quantity, numericality: { greater_than: -1 }
  validates :cost, numericality: { greater_than: 0 }
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :offer
  validates :quantity, numericality: { greater_than: 0 }
  validates :offer, presence: true
  validates :lastname, presence: true, length: { minimum: 2 }
  validates :street, presence: true
  validates :zip, presence: true, length: { is: 5 }
  validates :city, presence: true
  validates :telephone, length: { in: 6..30 }, presence: true, if: :without_email?
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i

  def without_email?
    self.email.blank?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_offer, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show, :create_order]
  helper_method :sort_column, :sort_direction


  # GET /offers
  # GET /offers.json
  def index
    @offers = Offer.order(sort_column + " " + sort_direction)
    @active_offers = Offer.where(active: true)
  end

  # GET /offers/1
  # GET /offers/1.json
  def show
    @order = Order.new
  end

  # GET /offers/new
  def new
    @offer = Offer.new
  end

  # GET /offers/1/edit
  def edit
  end

  # POST /offers
  # POST /offers.json
  def create
    @offer = Offer.new(offer_params)

    respond_to do |format|
      if @offer.save
        format.html { redirect_to offers_path, notice: 'Angebot erfolgreich erstellt' }
        format.json { render :show, status: :created, location: @offer }
      else
        format.html { render :new }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offers/1
  # PATCH/PUT /offers/1.json
  def update
    respond_to do |format|
      if @offer.update(offer_params)
        format.html { redirect_to @offer, notice: 'Angebot erfolgreich aktualisiert' }
        format.json { render :show, status: :ok, location: @offer }
      else
        format.html { render :edit }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1
  # DELETE /offers/1.json
  def destroy
    @offer.destroy
    respond_to do |format|
      format.html { redirect_to offers_url, notice: 'Angebot erfolgreich gelöscht' }
      format.json { head :no_content }
    end
  end

  def create_order
    @order = Order.new(order_params)
    @offer = Offer.find(params[:id])

    respond_to do |format|
      if @order.save
        format.html { redirect_to @offer, notice: 'Anfrage versendet! Es wird sich in den kommenden Tagen jemand von uns bei Ihnen melden' }
        format.json { render :index, status: :created, location: @offer }
      else
        format.html { render :show }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_offer
    @offer = Offer.find(params[:id])
  end

  def sort_column
    params[:sort] || "active"
  end

  def sort_direction
    params[:direction] || "desc"
  end


  # Never trust parameters from the scary internet, only allow the white list through.
  def offer_params
    params.require(:offer).permit(
      :image,
      :name,
      :description,
      :created_at,
      :quantity,
      :cost,
      :active
    )
  end

  def order_params
    params.require(:order).permit(
      :quantity,
      :received_at,
      :firstname,
      :lastname,
      :telephone,
      :email,
      :street,
      :zip,
      :city,
      :comment,
      :finished,
      :offer_id
    )
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  helper_method :sort_column, :sort_direction

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.joins(:offer).order(sort_column + " " + sort_direction)
  end


  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to orders_path, notice: 'Bestellung erfolgreich erstellt' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Bestellung erfolgreich aktualisiert' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Bestellung erfolgreich gelöscht' }
      format.json { head :no_content }
    end
  end


  private

    def sort_column
      params[:sort] || "received_at"
    end

    def sort_direction
      params[:direction] || "desc"
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(
        :quantity,
        :received_at,
        :firstname,
        :lastname,
        :telephone,
        :email,
        :street,
        :zip,
        :city,
        :comment,
        :finished,
        :offer_id
      )
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.order("email ASC")
  end

  def settings
  end

  def update_settings
    if params[:user][:password].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end

    if current_user.update_attributes(user_params)
      sign_in(current_user, bypass: true)
      redirect_to user_settings_path, notice: 'Passwort geändert'
    else
      render action: 'settings'
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :email,
      :password,
      :password_confirmation
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_controller?(controller)
    params[:controller] == controller
  end

  def sortable(column, title = nil)
    title ||= column.titleize
    direction = (column == params[:sort] && params[:direction] == "asc") ? "desc" : "asc"
    link_to title, params.merge(:sort => column, :direction => direction)
  end
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/layouts/_administration.html.erb
<nav class="top-bar" data-topbar>
  <section class="top-bar-section">
    <ul class="left">
      <li class="<%= 'active' if current_controller?('offers') %>">
        <%= link_to t('.offers'), offers_path %></li>
      <li class='divider'></li>
      <li class="<%= 'active' if current_controller?('orders') %>">
        <%= link_to t('.orders'), orders_path %></li>
    </ul>


    <ul class="right">
      <li><%= link_to(fa_icon("cog"), user_settings_path) %></li>
      <li class='divider'></li>
      <li><%= link_to 'Abmelden', destroy_user_session_path, method: :delete %></li>
    </ul>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=1000" />

    <title><%= content_for?(:title) ? yield(:title) : "Mini Store" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="row" id="content">
      <%= render 'layouts/administration' if user_signed_in? %>

        <% flash.each do |key, value| %>
          <div data-alert class="alert-box <%= key %>"><%= value %></div>
        <% end %>

      <%= yield %>

      <%= javascript_include_tag "application" %>
    </div>
  </body>
</html>

app/views/offers/_form.html.erb
<%= simple_form_for @offer do |f| %>
  <% if @offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= @offer.errors.count %> Fehler beim Erstellen eines Angebots aufgetreten</h2>

      <ul>
      <% @offer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= image_tag @offer.image.url(:medium) if @offer.image.present? %>
    <%= f.file_field :image %>
  </div>

  <div class="field">
    <%= f.label t ".name" %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label t ".description" %>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label t ".created_at" %>
    <%= Time.now %>
  </div>
  <div class="field">
    <%= f.label t ".quantity" %>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label t ".cost" %>
    <%= f.text_field :cost %>
  </div>
  <div class="field">
    <%= f.label t ".active" %>
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit 'Speichern', class: 'button small success centered' %>
  </div>
<% end %>

app/views/offers/edit.html.erb
<div class="large-12 columns">
  <h2><%= link_to(fa_icon("caret-left"), offer_path(@offer)) %> Angebot bearbeiten</h2>

  <%= render 'form' %>
</div>

app/views/offers/index.html.erb
<% if user_signed_in? %>
  <div class="large-12 columns">
    <div class="bottom-space">
      <%= link_to(fa_icon("plus-square 2x"), new_offer_path) %>
    </div>
  </div>

  <table>
    <thead>
      <tr>
        <th></th>
        <th><%= sortable "name", (t ".name") %></th>
        <th><%= sortable "description", (t ".description") %></th>
        <th><%= sortable "created_at", (t ".created_at") %></th>
        <th><%= sortable "quantity", (t ".quantity") %></th>
        <th><%= sortable "cost", (t ".cost") %></th>
        <th colspan="1"></th>
      </tr>
    </thead>

    <tbody>
      <% @offers.each do |offer| %>
        <tr>
          <td><%= link_to image_tag(offer.image.url(:thumb)), offer_path(offer) %></td>
          <td><%= offer.name %></td>
          <td><%= offer.description %></td>
          <td><%= offer.created_at %></td>
          <td><%= offer.quantity %></td>
          <td><%= number_to_currency( offer.cost, locale: :de) %></td>
          <% if offer.active == true %>
            <td><%= link_to(fa_icon("check-circle 2x"), offer_path(offer)) %></td>
          <% else %>
            <td><%= link_to(fa_icon("times-circle 2x"), offer_path(offer)) %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>

  <table>
    <thead>
      <tr>
        <th></th>
        <th><%=t ".name" %></th>
        <th><%=t ".description" %></th>
        <th><%=t ".cost" %></th>
        <th colspan="1"></th>
      </tr>
    </thead>

    <tbody>
      <% @active_offers.each do |offer| %>
        <tr>
          <td><%= link_to image_tag(offer.image.url(:thumb)), offer_path(offer) if offer.image.present? %></td>
          <td><%= offer.name %></td>
          <td><%= offer.description %></td>
          <td><%= number_to_currency( offer.cost, locale: :de) %></td>
          <td><%= link_to t('button.order'), offer, class: 'button tiny right' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

<% end %>

app/views/offers/new.html.erb
<div class="large-12 columns">
  <h2><%= link_to(fa_icon("caret-left"), offers_path) %> Neues Angebot</h2>

  <%= render 'form' %>
</div>

app/views/offers/show.html.erb
<div class="large-6 columns">
  <h2><%= link_to(fa_icon("caret-left"), offers_path) %> <%= @offer.name %></h2>

  <p>
    <%= image_tag @offer.image.url(:medium) if @offer.image.present? %>
  </p>

  <p>
    <strong><%=t ".description" %>:</strong>
    <%= @offer.description %>
  </p>

  <% if user_signed_in? %>
    <p>
      <strong><%=t ".created_at" %>:</strong>
      <%= @offer.created_at %>
    </p>
    <p>
      <strong><%=t ".quantity" %>:</strong>
      <%= @offer.quantity %>
    </p>
  <% end %>

  <p>
    <strong><%=t ".cost" %>:</strong>
    <%= number_to_currency( @offer.cost, locale: :de) %>
  </p>

  <% if user_signed_in? %>
    <p>
      <strong><%=t ".active" %>:</strong>
      <% if @offer.active == true %>
        <td><i class="fa fa-check-circle fa-2x"></i></td>
      <% else %>
         <td><i class="fa fa-times-circle fa-2x"></i></td>
      <% end %>
    </p>
  <% end %>

</div>

<% if current_user == nil %>
  <div class="large-6 columns">
    <%= simple_form_for @order, url: create_order_path, :method => 'post' do |f| %>
      <% if @order.errors.any? %>
        <div id="error_explanation">
          <h2><%= @order.errors.count %> Fehler bei der Bestellung</h2>

          <ul>
          <% @order.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <%= f.input :received_at, :as => :hidden, :input_html => { :value => Time.now } %>

      <%= f.input :offer_id, :as => :hidden, :input_html => { :value => @offer.id } %>

      <div class="field large-2 columns">
        <%= f.label t ".quantity" %>
        <%= f.number_field :quantity %>
      </div>
      <div class="field large-5 columns">
        <%= f.label t ".firstname" %>
        <%= f.text_field :firstname %>
      </div>
      <div class="field large-5 columns">
        <%= f.label t ".lastname" %>
        <%= f.text_field :lastname %>
      </div>
      <div class="field large-6 columns">
        <%= f.label t ".telephone" %>
        <%= f.text_field :telephone %>
      </div>
      <div class="field large-6 columns">
        <%= f.label t ".email" %>
        <%= f.text_field :email %>
      </div>
      <div class="field large-4 columns">
        <%= f.label t ".street" %>
        <%= f.text_field :street %>
      </div>
      <div class="field large-4 columns">
        <%= f.label t ".zip" %>
        <%= f.text_field :zip %>
      </div>
      <div class="field large-4 columns">
        <%= f.label t ".city" %>
        <%= f.text_field :city %>
      </div>
      <div class="field large-12 columns">
        <%= f.label t ".comment" %>
        <%= f.text_field :comment %>
      </div>
      <div class="actions">
        <%= f.submit 'Anfragen', class: 'button small success right' %>
      </div>
    <% end %>
  </div>
<% end %>

<div class="large-12 columns">
  <% if user_signed_in? %>
    <%= link_to t('button.edit'), edit_offer_path(@offer), class: 'button small' %>
    <%= link_to t('button.destroy'), @offer, method: :delete,
    data: { confirm: 'Sind Sie sicher?' }, class: 'button alert small right' %>
  <% end %>
</div>

app/views/orders/_form.html.erb
<%= simple_form_for @order do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= @order.errors.count %> Fehler beim Erstellen einer Bestellung aufgetreten</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field large-4 columns">
    <%= f.input :received_at,
    as: :string,
    input_html: { class: 'timepicker' } %>
  </div>
  <div class="field large-4 columns">
    <%= f.label t ".quantity" %>
    <%= f.number_field :quantity %>
  </div>
  <div class="field large-4 columns">
    <%= f.association :offer %>
  </div>
  <div class="field large-6 columns">
    <%= f.label t ".firstname" %>
    <%= f.text_field :firstname %>
  </div>
  <div class="field large-6 columns">
    <%= f.label t ".lastname" %>
    <%= f.text_field :lastname %>
  </div>
  <div class="field large-6 columns">
    <%= f.label t ".telephone" %>
    <%= f.text_field :telephone %>
  </div>
  <div class="field large-6 columns">
    <%= f.label t ".email" %>
    <%= f.text_field :email %>
  </div>
  <div class="field large-4 columns">
    <%= f.label t ".street" %>
    <%= f.text_field :street %>
  </div>
  <div class="field large-4 columns">
    <%= f.label t ".zip" %>
    <%= f.text_field :zip %>
  </div>
  <div class="field large-4 columns">
    <%= f.label t ".city" %>
    <%= f.text_field :city %>
  </div>
  <div class="field large-12 columns">
    <%= f.label t ".comment" %>
    <%= f.text_field :comment %>
  </div>
  <div class="field large columns">
    <%= f.label t ".finished" %>
    <%= f.check_box :finished %>
  </div>
  <div class="actions">
    <%= f.submit 'Speichern', class: 'button small success centered' %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<div class="large-12 columns">
  <h2><%= link_to(fa_icon("caret-left"), order_path(@order)) %> Bestellung bearbeiten</h2>

  <%= render 'form' %>
</div>

app/views/orders/index.html.erb
<% if user_signed_in? %>
  <div class="large-12 columns">
    <div class="bottom-space">
      <%= link_to(fa_icon("plus-square 2x"), new_order_path) %>
    </div>
  </div>
  <table>
    <thead>
      <tr>
        <th><%= sortable "received_at", (t ".received_at") %></th>
        <th><%= sortable "quantity", (t ".quantity") %></th>
        <th><%= sortable "name", (t "offer") %></th>
        <th><%= sortable "lastname", (t ".name") %></th>
        <th><%= sortable "comment", (t ".comment") %></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td><%= link_to order.received_at, order_path(order) %></td>
          <td><%= order.quantity %></td>
          <td><%= order.offer.name if order.offer.present? %></td>
          <td>
            <% if order.firstname.present? %>
              <%= order.firstname %>
            <% end %>
            <b><%= order.lastname %></b>
          </td>
          <td><%= order.comment %></td>
          <% if order.finished == true %>
            <td><%= link_to(fa_icon("thumbs-up 2x"), order_path(order)) %></td>
          <% else %>
            <td><%= link_to(fa_icon("spinner spin 2x"), order_path(order)) %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/orders/new.html.erb
<div class="large-12 columns">
  <h2><%= link_to(fa_icon("caret-left"), orders_path) %> Neue Bestellung</h2>

  <%= render 'form' %>
</div>

app/views/orders/show.html.erb
  <div class="large-12 columns">
    <h2><%= link_to(fa_icon("caret-left"), orders_path) %> <%= @order.quantity %>x <%= @order.offer.name if @order.offer.present? %> <%= "für " + @order.lastname if @order.lastname.present? %></h2>
  <p>
    <strong><%=t ".received_at" %>:</strong>
    <%= @order.received_at %>
  </p>

  <p>
    <strong><%=t ".order" %>:</strong>
    <%= @order.quantity %>x <%= link_to @order.offer.name, @order.offer, :target => '_blank' if @order.offer.present? %>
  </p>

  <p>
    <strong><%=t ".firstname" %>:</strong>
    <%= @order.firstname %>
  </p>

  <p>
    <strong><%=t ".lastname" %>:</strong>
    <%= @order.lastname %>
  </p>

  <p>
    <strong><%=t ".telephone" %>:</strong>
    <%= @order.telephone %>
  </p>

  <p>
    <strong><%=t ".email" %>:</strong>
    <%= @order.email %>
  </p>

  <p>
    <strong><%=t ".street" %>:</strong>
    <%= @order.street %>
  </p>

  <p>
    <strong><%=t ".zip" %>:</strong>
    <%= @order.zip %>
  </p>

  <p>
    <strong><%=t ".city" %>:</strong>
    <%= @order.city %>
  </p>

  <p>
    <strong><%=t ".comment" %>:</strong>
    <%= @order.comment %>
  </p>

  <p>
    <strong><%=t ".finished" %>:</strong>
    <% if @order.finished == true %>
      <td><i class="fa fa-thumbs-up fa-2x"></i></td>
    <% else %>
      <td><i class="fa fa-spinner fa-spin fa-2x"></i></td>
    <% end %>
  </p>

  <%= link_to t('button.edit'), edit_order_path(@order), class: 'button small' %>
  <%= link_to t('button.destroy'), @order, method: :delete,
    data: { confirm: 'Sind Sie sicher?' }, class: 'button alert small right' %>
</div>

app/views/users/index.html.erb
<div class="large-12 columns">
  <h2><%= link_to(fa_icon("caret-left"), user_settings_path) %> <%=t 'users.title' %></h2>
</div>

<table>
  <thead>
    <tr>
      <th><%=t "users.email" %></th>
      <th><%=t "users.current_sign_in" %></th>
      <th><%=t "users.last_sign_in" %></th>
      <th><%=t "users.created_at" %></th>
      <th><%=t "users.sign_in_count" %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.current_sign_in_at %><br><%= user.current_sign_in_ip %></td>
        <td><%= user.last_sign_in_at %><br><%= user.last_sign_in_ip %></td>
        <td><%= user.created_at %></td>
        <td><%= user.sign_in_count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/settings.html.erb
<div class="large-12 columns">
  <h2>Einstellungen</h2>

  <p>Eingeloggt als <%= current_user.email %></p>
  <p>Logins: <%= current_user.sign_in_count %></p>
  <p>Erstellt: <%= current_user.created_at %></p>
  <%= link_to 'Benutzerverwaltung', users_path, class: 'button small' %>

  <%= simple_form_for current_user, as: :user, url: user_settings_path do |f| %>

    <% if notification = f.error_notification %>
      <div class="alert-message"><%= notification %></div>
    <% end %>

    <%= f.input :password %>

    <%= f.input :password_confirmation %>

    <div class="right">
      <%= f.submit 'Speichern', class: 'button small success', data: { confirm: 'Passwort ändern?' }%>
    </div>
  <% end %>
</div>